version: '3'

services:
  database: 
    image: mysql:latest
    container_name: database
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
    volumes:
      - ./dbdata:/var/lib/mysql
  backend:
    build: ./backend
    container_name: backend
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/var/www/html
      - ./storage:/var/www/html/storage  # Adiciona este volume para acessar o relatório
    depends_on:
      - database
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    user: root
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    volumes:
      - ./jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"